import type { NextPage } from "next";
import { db } from "../../Firebase/firebase";
import Head from "next/head";
import styles from "/styles/sass/work.module.scss";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { Base } from "../../components";
import { work } from "../../types/firebase";

const Work: NextPage = () => {
  const [work, setWork] = useState<work | null>();
  const router = useRouter();

  useEffect(() => {
    getWork();
  }, [router.query.wid]);

  const parser = (text: string): string => {
    if (!text || text === "") {
      return "";
    } else {
      return text.replace(/\\n/g, "\n");
    }
  };

  const getWork = async () => {
    await db
      .collection("works")
      .doc(router.query.wid as string)
      .get()
      .then((doc) => {
        doc && setWork(doc.data() as work);
      });
  };

  const divideTagImageVideo = (work: work) => {
    switch (work?.type) {
      case "image":
        return <img alt={""} src={work.work_path} />;
      case "video":
        return <video autoPlay playsInline muted src={work.work_path} />;
      default:
        console.log("type undefined");
    }
  };

  return (
    <div>
      <Head>
        <title>WORK | KAMATA YUSAKU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base isFooter={true}>
        <div className={styles.work}>
          <div className={styles.work__content}>
            <h1 className={styles.work__content__title}>{work?.title}</h1>
            <h4 className={styles.work__content__subtitle}>
              {work?.sub_title}
            </h4>
            {work && divideTagImageVideo(work)}
            <p className={styles.work__content__description}>
              {work && parser(work.description)}
            </p>
          </div>
        </div>
      </Base>
    </div>
  );
};

export default Work;
