import type { NextPage } from "next";
import { db } from "../Firebase/firebase";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "/styles/sass/index.module.scss";
import Link from "next/link";
import { Base } from "../components";
import { work } from "../types/firebase";

const Top: NextPage = () => {
  const [works, setWorks] = useState<work[]>([]);

  useEffect(() => {
    getWorks();
  }, []);

  const getWorks = async () => {
    await db
      .collection("works")
      .get()
      .then((snapshot) => {
        const works: work[] = [];
        snapshot.docs.forEach((doc) => {
          works.push({ id: doc.id, ...doc.data() } as work);
        });
        setWorks(works);
      });
  };

  const switchTagImageVideo = (work: work) => {
    switch (work.type) {
      case "image":
        return <img alt={""} src={work.head_path} />;
      case "video":
        return <video autoPlay playsInline muted src={work.head_path} />;
      default:
        console.log("type undefined");
    }
  };

  return (
    <>
      <Head>
        <title>WORKS | KAMATA YUSAKU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base isFooter={true}>
        <div className={styles.works}>
          <ul className={styles.works__wrapper}>
            {works.map((work, index) => (
              <li key={index} className={styles.works__wrapper__work}>
                <Link href={`/work/${work.id}`}>
                  <a>
                    {switchTagImageVideo(work)}
                    <div className={styles.works__wrapper__work__text}>
                      <span
                        className={styles.works__wrapper__work__text__title}
                      >
                        {work.title}
                      </span>
                      <span
                        className={styles.works__wrapper__work__text__subtitle}
                      >
                        {work.sub_title}
                      </span>
                    </div>
                  </a>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </Base>
    </>
  );
};

export default Top;
